### ISSUE TITLE
심심해서 적어본...

### ISSUE THREAD

**Issue by hyj378** [hyj378/ArtificialIntelligence#10]
개념만 조금 정리했어요!
모델 만들때는 출처 블로그 말고 [이 블로그](https://wdprogrammer.tistory.com/42) 참고하면 좋을것 같아요
[출처](https://brunch.co.kr/@learning/8)
SNS 에서 수집한  '현실 세계의 한국어 텍스트'데이터에서 학습을 위한 의미있는 정보를 뽑아내는것은 쉬운일이 아니다. 또한 한국어 텍스트 자료에 영미권 연구자가 만든 자연어 처리 기계학습 모델을 그대로 적용하면, 대부분 거의 작동하지 않는다. 이러한 어려움을 극복하기 위해 규칙 기반(rule-based)의 접근법을 제외하고는 두가지 방안이 있다

* 형태소 분석을 이용해 의미적(semantic)인 부분이 아닌것을 제거 후 기계학습 기법 적용
장점: 한국어 어휘에서 구문적인 특징을 제거함으로서 코퍼스(?)상에서 등장하는 어휘의 종류를 줄일 수 있다(조사의 역활 등)
단점: 구문적 특성을 제거하였으므로 텍스트의 의미를 일부 잃어버릴 수 있다

*어휘를 글자수준으로 쪼개어 기계학습 기법 적용
장점: 위의 단점을 피할 수 있다
단점: 어휘 임베딩을 사용할 수 없다.
 
자연어 처리를 위한 인공신경망 모델의 경우 학습해야하는 파라미터중 매우 큰 비중을 차지하는 것이 어휘임베딩 레이어 이다.
 어휘임베딩 레이어
* 레이어의 적절한 초기값을 제공
* 확보한 데이터셋의 규모가 작을 때 특히 중요

모델에 대하여
[word2vecter에 대하여](https://aws.amazon.com/ko/blogs/korea/amazon-sagemaker-blazingtext-parallelizing-word2vec-on-multiple-cpus-or-gpus/) 
[word2vecter 설명 블로그](http://doc.mindscale.kr/km/unstructured/11.html) 

의미적 정보 뿐 아니라 구문적 정보까지 학습할 수 있는 어휘 임베딩을 위해 링크의 블로그는 SGNS를 적용했다. 
블로그의 학습 과정

* SGNS를 기반으로 FastText를 적용하고
* CNN/RNN기반으로 어휘를 임베딩하는 모형을 만들고
* 기존 어휘수준 임베딩에 구문적 특징을 학습과정에 추가하여 Word2Vec를 학습한다
 
SGNS는 (Skip-Gram with Negative Sampling)의 줄임말이다.
word2Vec는 아래와 같은 구조를 가진다
![image](https://user-images.githubusercontent.com/41140561/58377457-0a9ab100-7fbc-11e9-8646-89baa6888fcb.png)
word2Vec는 단어에 대해 고밀도 벡터표현을 학습하는 알고리즘이다. 이는 비지도 학습과정으로 학습된 고밀도 임베딩 벡터의 관점에서, 주변의 단어로 부터 해당단어를 직접적으로 예측한다.  이는 위 그림처럼 CBOW (Contextual Bag-Of-Words)와 SGNS (Skip-Gram with Negative Sampling)의 두 가지 모델 아키텍처로 이루어진다.
CBOW는 어떤 문맥이 주어진 조건 하에서 단어를 예측하고, skip-gram은 어떤 단어가 주어졌을 때 해당 단어의 문맥을 예측한다.

FastText란 Word2Vec와 같은 단어임베딩의 한 종류이다 이는 다양한 언어에 적용되어 어휘 수준(word-level) SGNS보다 어휘의 구문적 특징을 잡아내는데 탁월하다. 한국어 어휘를 자모단위로 분해한 후 FastText를 적용한다고 한다.
(자모(子母, 字母)또는 낱자는 문자 체계의 한 요소로서 한글에서는 모음인 ㅏ나 ㅗ, ㄱ,ㅎ 따위를 일컫는다.)

**Comment by hyj378** [comment]
[cmd창에서 UTF-8을 깨짐현상 없이 보고싶을때](https://extrememanual.net/12502)
![image](https://user-images.githubusercontent.com/41140561/58385420-25583e80-802b-11e9-9230-9a4bcd042526.png)
파일이 커서 csv나 메모장으로 열리지 않으면 type명령어쓰고, chcp 65001로 UTF-8깨짐 막으면 좋아요!

**Comment by kimkyeongnam** [comment]
좋은 정보 감사합니다! :-)

**Comment by hyj378** [comment]
[okt사용.pptx](https://github.com/hyj378/ArtificialIntelligence/files/3284357/okt.pptx)
