### ISSUE TITLE
감정의 5가지 분류와 대표 이모티콘들

### ISSUE THREAD

**Issue by min942773** [hyj378/ArtificialIntelligence#17]
![56940180-afee7080-6b47-11e9-81a3-c08fb33bf630](https://user-images.githubusercontent.com/41141885/58710346-0ecd3100-83f7-11e9-89f6-63701c65aebb.png)
감정 모델을 참고하여 어떤 감정을 뽑아 이를 라벨링에 사용할지 논의한 결과 애정, 분노, 슬픔, 피곤, 공포 5가지가 서로 뚜렷하게 구분되며 이모티콘으로도 많이 나와있는 감정이었습니다. 그래서 이 5가지로 감정을 분류하고 이를 대표하는 이모티콘을 선정하여 크롤링하였습니다.

애정 : 😍, 😘, 😙, 🤭, 💘 
분노 : 😤, 😡, 😠, 🤬, 👿 
슬픔 : 😥, 😢, 😭, 💦  
피곤 : 😔, 😑, 😐, 😞  
공포 : 😨, 😰, 😱

**Comment by hyj378** [comment]
공포
* tweetscreept로 (더 긴 기간)
[key 😨, 😰, 😱](https://drive.google.com/file/d/1--6MicDSrK2L8DYia78t6MmYDRK-iCuH/view?usp=sharing)


* tweepy로
[key 😨, 😰, 😱](https://drive.google.com/file/d/1-CTqZ2gWnko7R9lxWTZNhmD52a3ObIT5/view?usp=sharing)
[key  😱](https://drive.google.com/file/d/1i7iYHPta_O4HbImhNkU1LP-P7DYtWrpM/view?usp=sharing)

**Comment by kimkyeongnam** [comment]
:triumph:, :rage:, :angry:, 🤬, :imp:

**Comment by kimkyeongnam** [comment]
이모티콘 감정 참고 사이트: [emojipedia](https://emojipedia.org/)
