### ISSUE TITLE
각자 크롤링할 감정

### ISSUE THREAD

**Issue by min942773** [hyj378/ArtificialIntelligence#18]
김경남 : 슬픔 😭
김민주 : 피곤 😔
유지인 : 분노 😤
이주혁 : 애정 😍
황유진 : 공포 😱

**Comment by hyj378** [comment]
공포
* tweetscreept로 (더 긴 기간)
[key 😱](https://drive.google.com/file/d/1--6MicDSrK2L8DYia78t6MmYDRK-iCuH/view?usp=sharing)
[key  😨, 😰, 😱](https://drive.google.com/file/d/1-S2h0sLwtgti1cQtZcm_sbOHZfTpZKEg/view?usp=sharing)

* tweepy로
[key 😱](https://drive.google.com/file/d/1-CTqZ2gWnko7R9lxWTZNhmD52a3ObIT5/view?usp=sharing)
[key  😨, 😰, 😱](https://drive.google.com/file/d/1i7iYHPta_O4HbImhNkU1LP-P7DYtWrpM/view?usp=sharing)

**Comment by min942773** [comment]
피곤

* tweetscraper로 크롤링
[😔, 😑, 😞](https://drive.google.com/file/d/1QBOkNa_9RgpjejRhaXG1oZ2w2CWyU8Ew/view?usp=sharing)

**Comment by kimkyeongnam** [comment]
슬픔
* tweetscraper로 크롤링
😡, 😠, 👿, 🤬, 😤

크롤링 결과 및 코드 [[link]](https://colab.research.google.com/drive/1XcKhInvid4NRbbGI-zAG5dYnRc_2QwsN)

(분노 이모티콘은 생각보다 결과가 많지 않네요.. 최대 5만개로 설정했는데 총 28755개 나왔습니당)

**Comment by jiin0217** [comment]
분노

-  twittercraper로 크롤링
   [😡😤👿☹😖😒](https://drive.google.com/drive/my-drive)

**Comment by jiin0217** [comment]
분노

-  twitterscraper로 크롤링
   [😡😤👿☹😖😒](https://docs.google.com/spreadsheets/d/1vatvv-7n3jRBZ2cjeJN5hks_r0aCN6jyZMvI5WqLxR0/edit?usp=sharing)

**Comment by zero5two4** [comment]
애정

-  twitterscraper로 크롤링
   [😍 😘 😙 🤭 💘](https://docs.google.com/spreadsheets/d/10PxJ_y7--_AeejL8xxvKExv_VwkJH2IgwyZtIaPnEiM/edit#gid=1156640768)

**Comment by zero5two4** [comment]
애정(@제거)

-  twitterscraper로 크롤링
   [😍 😘 😙 🤭 💘](https://drive.google.com/file/d/1--vl4UEiqDVxSrA1yXfM7_GJ7ruyPrtp/view?usp=sharing)
