### ISSUE TITLE
Word2Vec 모델

### ISSUE THREAD

**Issue by kimkyeongnam** [hyj378/ArtificialIntelligence#23]
https://colab.research.google.com/drive/1aJQPx8NNgVPxikXxxJn6RVHC2nUqeslH

**Comment by min942773** [comment]
K-means를 이용해 clustering을 추가했습니다.
https://colab.research.google.com/drive/1fL7c3ZXnuOPxVs5JLvTNmeK_ZZvWV8so
![image](https://user-images.githubusercontent.com/41141885/59244204-7fbde580-8c4e-11e9-99be-067aea1cf784.png)
군집에 따라 색이 다릅니당
