### ISSUE TITLE
NLP Steps

### ISSUE THREAD

**Issue by kimkyeongnam** [hyj378/ArtificialIntelligence#26]
![nlp step](https://user-images.githubusercontent.com/38516906/59241849-39638900-8c44-11e9-853d-b735270e342a.png)

출처: https://inspiringpeople.github.io/data%20analysis/word_embedding/

**Comment by hyj378** [comment]
[전처리](https://colab.research.google.com/drive/1x059gfqeeUvcbriP-6B5LYzKtdmawsny#scrollTo=GC31sHLfYUdB)
