### ISSUE TITLE
스터디 같이 하실 분 구해용

### ISSUE THREAD

**Issue by hyj378** [hyj378/ArtificialIntelligence#3]
텐서플로우를 기본으로 머신러닝 스터디 같이 하실분 구합니다!

<img src="https://user-images.githubusercontent.com/41140561/55130438-389b7a80-515e-11e9-9d81-7c4ae67fc653.png" width="30%" height="45%">
<img src="https://user-images.githubusercontent.com/41140561/55130457-4bae4a80-515e-11e9-9311-df7ce1b8530c.png" width="30%" height="45%">

이 책이나 다른책 원하시는분 말씀해주세요!

**Comment by kimkyeongnam** [comment]
저요저요!!!!!
![☆여기에저장](https://user-images.githubusercontent.com/38516906/55138158-1e6d9680-5176-11e9-87ea-c4f1244ad6b7.png)
이 책도 개인적으로 같이 공부했으면 좋겠어요 ㅎㅎ..

**Comment by kimkyeongnam** [comment]
일단 저희 둘이 스터디하고 있겠습니다!
매주 **화요일 오후8시~10시**로 일정 잡았어요~~ :-)

**Comment by zero5two4** [comment]
오호! 저도 할게요!!!

**Comment by kimkyeongnam** [comment]
인터넷 검색하다가 좋은 책 찾아서 댓글달아요!
![image](https://user-images.githubusercontent.com/38516906/55681860-55a62980-5966-11e9-9cec-c721d9eb17ee.png)

올해 1월에 나온 책인데 목록 중에
* 감정분류기 만들기
* 주어진 문장을 분석해 적절한 이모티콘을 제안하는 AI만들기

이렇게 있더라고요. 한번 참고해보면 좋을 것 같습니다 :-)
