### ISSUE TITLE
참고 주소

### ISSUE THREAD

**Issue by hyj378** [hyj378/ArtificialIntelligence#5]
[실행영상 유튜브](https://www.youtube.com/watch?v=B-JF2zVHbQE)

**Comment by kimkyeongnam** [comment]
![image](https://user-images.githubusercontent.com/38516906/55681860-55a62980-5966-11e9-9cec-c721d9eb17ee.png)

**Comment by kimkyeongnam** [comment]
[Korean Sentiment Analysis Corpus: 한국어 감정 및 의견 분석 코퍼스](http://word.snu.ac.kr/kosac/publications.php)
[The Korean Question Answering Dataset](https://korquad.github.io/)
[Mojitok(youtube)](https://www.youtube.com/watch?v=B-JF2zVHbQE)
[Mojitok(github)](https://github.com/claude-zhou/MojiTalk/blob/master/emoji-test.txt)
[Emoji unicode](http://unicode.org/emoji/charts/full-emoji-list.html)
