### ISSUE TITLE
자료조사 레포지토리

### ISSUE THREAD

**Issue by kimkyeongnam** [hyj378/ArtificialIntelligence#8]
**모델**: https://github.com/kimkyeongnam/Artificial_Intelligence_Model   (Private)

**Comment by unizard** [comment]
@kimkyeongnam 음... repo 에 repo네?ㅎㅎ
Private인 이유를 물어봐도 될련지요?

**Comment by kimkyeongnam** [comment]
@unizard 논문 중 그대로 올리면 저작권 위배되는게 몇 가지 있어서 임시로 잠시 만들었습니다! 나중에 정리할게요 ㅎ.ㅎ...
